version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      - postgres

volumes:
    pg_data:
