"""add tables for Clans

Revision ID: 61a277d38800
Revises: ad40e7597121
Create Date: 2024-09-22 18:58:57.942296

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61a277d38800"
down_revision: Union[str, None] = "ad40e7597121"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=25), nullable=False),
        sa.Column("short_name", sa.String(length=3), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("rang", sa.Integer(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("is_ghost", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_clans_id"), "clans", ["id"], unique=False)
    op.create_table(
        "requests_to_clans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("clan_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("date_create", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_requests_to_clans_id"), "requests_to_clans", ["id"], unique=False
    )
    op.create_table(
        "subscribe_to_clans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("clan_id", sa.Integer(), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "Глава",
                "Заместитель",
                "Старейшина",
                "Офицер",
                "Участник",
                name="role_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("date_create", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscribe_to_clans_id"), "subscribe_to_clans", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscribe_to_clans_id"), table_name="subscribe_to_clans")
    op.drop_table("subscribe_to_clans")
    op.drop_index(op.f("ix_requests_to_clans_id"), table_name="requests_to_clans")
    op.drop_table("requests_to_clans")
    op.drop_index(op.f("ix_clans_id"), table_name="clans")
    op.drop_table("clans")
    # ### end Alembic commands ###
