"""correct think btw Biome and boss_abilities

Revision ID: 5e74023c523d
Revises: eb55e9a8e346
Create Date: 2024-09-11 13:18:32.713100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e74023c523d"
down_revision: Union[str, None] = "eb55e9a8e346"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("boss_abilities", sa.Column("biome_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "boss_abilities", "biomes", ["biome_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "boss_abilities", type_="foreignkey")
    op.drop_column("boss_abilities", "biome_id")
    # ### end Alembic commands ###
