"""correct

Revision ID: 294774592add
Revises: 2c47b8a19771
Create Date: 2024-09-11 17:23:50.833885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "294774592add"
down_revision: Union[str, None] = "2c47b8a19771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("biomes", sa.Column("level_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "biomes", "biome_levels", ["level_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "biomes", type_="foreignkey")
    op.drop_column("biomes", "level_id")
    # ### end Alembic commands ###
