"""correct think btw Biome and BiomeLevel

Revision ID: 4d1a2962a38d
Revises: 5e74023c523d
Create Date: 2024-09-11 17:00:51.818827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d1a2962a38d"
down_revision: Union[str, None] = "5e74023c523d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biome_abilities",
        sa.Column("biome_level_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["biome_level_id"],
            ["biome_levels.id"],
        ),
        sa.PrimaryKeyConstraint("biome_level_id"),
    )
    op.add_column(
        "boss_abilities", sa.Column("biome_level_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "boss_abilities", "biome_levels", ["biome_level_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "boss_abilities", type_="foreignkey")
    op.drop_column("boss_abilities", "biome_level_id")
    op.drop_table("biome_abilities")
    # ### end Alembic commands ###
