"""correct

Revision ID: dbca093a078a
Revises: 31224bc5737c
Create Date: 2024-09-12 00:00:42.443906

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dbca093a078a"
down_revision: Union[str, None] = "31224bc5737c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_biome_levels_id"), "biome_levels", ["id"], unique=False)
    op.create_index(op.f("ix_biomes_id"), "biomes", ["id"], unique=False)
    op.create_index(op.f("ix_bosses_boss_id"), "bosses", ["boss_id"], unique=False)
    op.create_index(op.f("ix_rewards_id"), "rewards", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rewards_id"), table_name="rewards")
    op.drop_index(op.f("ix_bosses_boss_id"), table_name="bosses")
    op.drop_index(op.f("ix_biomes_id"), table_name="biomes")
    op.drop_index(op.f("ix_biome_levels_id"), table_name="biome_levels")
    # ### end Alembic commands ###
