"""correct

Revision ID: a45d46e702b5
Revises: 294774592add
Create Date: 2024-09-11 18:40:42.883492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a45d46e702b5"
down_revision: Union[str, None] = "294774592add"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("biomes_level_id_fkey", "biomes", type_="foreignkey")
    op.drop_column("biomes", "level_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "biomes", sa.Column("level_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "biomes_level_id_fkey", "biomes", "biome_levels", ["level_id"], ["id"]
    )
    # ### end Alembic commands ###
