"""add FK CLAN-SubReq

Revision ID: 15301ba4ae21
Revises: a6281cb57e86
Create Date: 2024-10-07 13:45:13.764820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15301ba4ae21"
down_revision: Union[str, None] = "a6281cb57e86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clans", sa.Column("subscribers_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "clans", "users", ["subscribers_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "clans", type_="foreignkey")
    op.drop_column("clans", "subscribers_id")
    # ### end Alembic commands ###
