"""correct

Revision ID: e4351b64caa8
Revises: dbca093a078a
Create Date: 2024-09-12 20:46:25.249070

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4351b64caa8"
down_revision: Union[str, None] = "dbca093a078a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_progress", sa.Column("player_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        "player_progress_player_fkey", "player_progress", type_="foreignkey"
    )
    op.create_foreign_key(None, "player_progress", "users", ["player_id"], ["id"])
    op.drop_column("player_progress", "player")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_progress",
        sa.Column("player", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "player_progress", type_="foreignkey")
    op.create_foreign_key(
        "player_progress_player_fkey", "player_progress", "users", ["player"], ["id"]
    )
    op.drop_column("player_progress", "player_id")
    # ### end Alembic commands ###
