"""add think btw User and PlayerProgress

Revision ID: eb55e9a8e346
Revises: 66c951a06ee7
Create Date: 2024-09-10 20:24:17.583647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb55e9a8e346"
down_revision: Union[str, None] = "66c951a06ee7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player_progress", sa.Column("player", sa.Integer(), nullable=True))
    op.add_column(
        "player_progress", sa.Column("difficult_lvl", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "player_progress", "users", ["player"], ["id"])
    op.add_column("rewards", sa.Column("icon", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rewards", "icon")
    op.drop_constraint(None, "player_progress", type_="foreignkey")
    op.drop_column("player_progress", "difficult_lvl")
    op.drop_column("player_progress", "player")
    # ### end Alembic commands ###
