"""correct

Revision ID: 2c47b8a19771
Revises: 4d1a2962a38d
Create Date: 2024-09-11 17:20:04.437688

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c47b8a19771"
down_revision: Union[str, None] = "4d1a2962a38d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("biome_abilities")
    op.drop_constraint(
        "boss_abilities_biome_level_id_fkey", "boss_abilities", type_="foreignkey"
    )
    op.drop_column("boss_abilities", "biome_level_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boss_abilities",
        sa.Column("biome_level_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "boss_abilities_biome_level_id_fkey",
        "boss_abilities",
        "biome_levels",
        ["biome_level_id"],
        ["id"],
    )
    op.create_table(
        "biome_abilities",
        sa.Column("biome_level_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["biome_level_id"],
            ["biome_levels.id"],
            name="biome_abilities_biome_level_id_fkey",
        ),
        sa.PrimaryKeyConstraint("biome_level_id", name="biome_abilities_pkey"),
    )
    # ### end Alembic commands ###
