"""change

Revision ID: 7892703a3851
Revises: c483673aa133
Create Date: 2024-09-12 21:07:35.563781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7892703a3851'
down_revision: Union[str, None] = 'c483673aa133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_classes_id'), 'character_classes', ['id'], unique=False)
    op.create_table('character_subclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.Column('character_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_classes.id'], ),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_subclasses_id'), 'character_subclasses', ['id'], unique=False)
    op.create_table('classes_abilities',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['character_classes.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'ability_id')
    )
    op.create_table('races_abilities',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'ability_id')
    )
    op.create_table('subclasses_abilities',
    sa.Column('subclass_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['character_subclasses.id'], ),
    sa.PrimaryKeyConstraint('subclass_id', 'ability_id')
    )
    op.drop_index('ix_character_archetypes_id', table_name='character_archetypes')
    op.drop_constraint('characters_archetype_id_fkey', 'characters', type_='foreignkey')
    op.drop_table('character_archetypes')
    op.drop_index('ix_item_tiers_id', table_name='item_tiers')
    op.drop_constraint('items_tier_id_fkey', 'items', type_='foreignkey')
    op.drop_table('item_tiers')
    op.drop_index('ix_ability_tiers_id', table_name='ability_tiers')
    op.drop_constraint('abilities_ability_tier_id_fkey', 'abilities', type_='foreignkey')
    op.drop_table('ability_tiers')
    op.drop_table('character_abilities')
    op.add_column('abilities', sa.Column('tier', sa.Integer(), nullable=False))

    trigger_condition_enum = sa.Enum(
        'ON_START', 'ON_MOTION_START', 'ON_COMMON_ATTACK', 'ON_ULTIMATE_ATTACK',
        'PASSIVE', 'ON_BUFF', 'ON_DEBUFF', 'ON_DEATH', 'ON_TEAMMATE_ATTACK',
        'ON_REVIVE', 'ON_SUMMONED', name='triggercondition'
    )
    trigger_condition_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('abilities', sa.Column('trigger_condition', trigger_condition_enum, nullable=False))
    op.drop_column('abilities', 'ability_tier_id')
    op.add_column('characters', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('subclass_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_foreign_key(None, 'characters', 'character_subclasses', ['subclass_id'], ['id'])
    op.create_foreign_key(None, 'characters', 'character_classes', ['class_id'], ['id'])
    op.drop_column('characters', 'archetype_id')
    op.drop_column('items', 'tier_id')
    op.add_column('multiplier_params', sa.Column('resistance', sa.Float(), nullable=True))
    op.drop_column('multiplier_params', 'accuracy')
    op.drop_column('multiplier_params', 'intelligence')
    op.drop_column('multiplier_params', 'magical_resistance')
    op.drop_column('multiplier_params', 'agility')
    op.drop_column('multiplier_params', 'strength')
    op.drop_column('multiplier_params', 'physical_resistance')
    op.alter_column('races', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('summand_params', sa.Column('resistance', sa.Float(), nullable=True))
    op.drop_column('summand_params', 'accuracy')
    op.drop_column('summand_params', 'intelligence')
    op.drop_column('summand_params', 'magical_resistance')
    op.drop_column('summand_params', 'agility')
    op.drop_column('summand_params', 'strength')
    op.drop_column('summand_params', 'physical_resistance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summand_params', sa.Column('physical_resistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('summand_params', sa.Column('strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('summand_params', sa.Column('agility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('summand_params', sa.Column('magical_resistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('summand_params', sa.Column('intelligence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('summand_params', sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('summand_params', 'resistance')
    op.alter_column('races', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('multiplier_params', sa.Column('physical_resistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('multiplier_params', sa.Column('strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('multiplier_params', sa.Column('agility', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('multiplier_params', sa.Column('magical_resistance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('multiplier_params', sa.Column('intelligence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('multiplier_params', sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('multiplier_params', 'resistance')
    op.add_column('items', sa.Column('tier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('archetype_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_column('characters', 'subclass_id')
    op.drop_column('characters', 'class_id')
    op.add_column('abilities', sa.Column('ability_tier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('abilities', 'trigger_condition')
    op.drop_column('abilities', 'tier')
    op.create_table('character_abilities',
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], name='character_abilities_ability_id_fkey'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_abilities_character_id_fkey'),
    sa.PrimaryKeyConstraint('character_id', 'ability_id', name='character_abilities_pkey')
    )
    op.create_table('ability_tiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ability_tiers_pkey')
    )
    op.create_index('ix_ability_tiers_id', 'ability_tiers', ['id'], unique=False)
    op.create_foreign_key('abilities_ability_tier_id_fkey', 'abilities', 'ability_tiers', ['ability_tier_id'], ['id'])
    op.create_table('item_tiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='item_tiers_pkey')
    )
    op.create_index('ix_item_tiers_id', 'item_tiers', ['id'], unique=False)
    op.create_table('character_archetypes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('multiplier_params_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summand_params_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], name='character_archetypes_multiplier_params_id_fkey'),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], name='character_archetypes_summand_params_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_archetypes_pkey')
    )
    op.create_index('ix_character_archetypes_id', 'character_archetypes', ['id'], unique=False)
    op.create_foreign_key('items_tier_id_fkey', 'items', 'item_tiers', ['tier_id'], ['id'])
    op.create_foreign_key('characters_archetype_id_fkey', 'characters', 'character_archetypes', ['archetype_id'], ['id'])
    op.drop_table('subclasses_abilities')
    op.drop_table('races_abilities')
    op.drop_table('classes_abilities')
    op.drop_index(op.f('ix_character_subclasses_id'), table_name='character_subclasses')
    op.drop_table('character_subclasses')
    op.drop_index(op.f('ix_character_classes_id'), table_name='character_classes')
    op.drop_table('character_classes')
    # ### end Alembic commands ###
