"""create migration

Revision ID: c483673aa133
Revises: 
Create Date: 2024-09-06 20:31:19.728517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c483673aa133'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_tiers_id'), 'ability_tiers', ['id'], unique=False)
    op.create_table('ability_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ability_types_id'), 'ability_types', ['id'], unique=False)
    op.create_table('character_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_types_id'), 'character_types', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('item_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_tiers_id'), 'item_tiers', ['id'], unique=False)
    op.create_table('multiplier_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=True),
    sa.Column('vitality', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('agility', sa.Float(), nullable=True),
    sa.Column('intelligence', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('physical_resistance', sa.Float(), nullable=True),
    sa.Column('magical_resistance', sa.Float(), nullable=True),
    sa.Column('critical_hit_chance', sa.Float(), nullable=True),
    sa.Column('evasion', sa.Float(), nullable=True),
    sa.Column('true_damage', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('spirit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_multiplier_params_id'), 'multiplier_params', ['id'], unique=False)
    op.create_table('summand_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Float(), nullable=True),
    sa.Column('vitality', sa.Float(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('agility', sa.Float(), nullable=True),
    sa.Column('intelligence', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('physical_resistance', sa.Float(), nullable=True),
    sa.Column('magical_resistance', sa.Float(), nullable=True),
    sa.Column('critical_hit_chance', sa.Float(), nullable=True),
    sa.Column('evasion', sa.Float(), nullable=True),
    sa.Column('true_damage', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('spirit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summand_params_id'), 'summand_params', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_id'), 'auth_sessions', ['id'], unique=False)
    op.create_table('character_archetypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_archetypes_id'), 'character_archetypes', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['item_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_table('users_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('character_type_id', sa.Integer(), nullable=True),
    sa.Column('archetype_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.Column('fragments', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('stardom', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archetype_id'], ['character_archetypes.id'], ),
    sa.ForeignKeyConstraint(['character_type_id'], ['character_types.id'], ),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('ability_tier_id', sa.Integer(), nullable=True),
    sa.Column('ability_type_id', sa.Integer(), nullable=True),
    sa.Column('summand_params_id', sa.Integer(), nullable=True),
    sa.Column('multiplier_params_id', sa.Integer(), nullable=True),
    sa.Column('chance', sa.Float(), nullable=True),
    sa.Column('summoned_character_id', sa.Integer(), nullable=True),
    sa.Column('summoned_quantity', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('healing', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_tier_id'], ['ability_tiers.id'], ),
    sa.ForeignKeyConstraint(['ability_type_id'], ['ability_types.id'], ),
    sa.ForeignKeyConstraint(['multiplier_params_id'], ['multiplier_params.id'], ),
    sa.ForeignKeyConstraint(['summand_params_id'], ['summand_params.id'], ),
    sa.ForeignKeyConstraint(['summoned_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abilities_id'), 'abilities', ['id'], unique=False)
    op.create_table('character_items',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'item_id')
    )
    op.create_table('character_abilities',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_abilities')
    op.drop_table('character_items')
    op.drop_index(op.f('ix_abilities_id'), table_name='abilities')
    op.drop_table('abilities')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('users_chats')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_character_archetypes_id'), table_name='character_archetypes')
    op.drop_table('character_archetypes')
    op.drop_index(op.f('ix_auth_sessions_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_summand_params_id'), table_name='summand_params')
    op.drop_table('summand_params')
    op.drop_index(op.f('ix_multiplier_params_id'), table_name='multiplier_params')
    op.drop_table('multiplier_params')
    op.drop_index(op.f('ix_item_tiers_id'), table_name='item_tiers')
    op.drop_table('item_tiers')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_character_types_id'), table_name='character_types')
    op.drop_table('character_types')
    op.drop_index(op.f('ix_ability_types_id'), table_name='ability_types')
    op.drop_table('ability_types')
    op.drop_index(op.f('ix_ability_tiers_id'), table_name='ability_tiers')
    op.drop_table('ability_tiers')
    # ### end Alembic commands ###
